### ISSUE TITLE
JPEGs with rotation exif isn't handled correctly

### ISSUE THREAD

**Issue by mortie** [Emilinya/Letterboxinator#1]
The code currently ignores rotation metadata. You can use the [ImageOps.exif_transpose](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.exif_transpose) function to get pillow to automatically deal with rotation metadata.

**Comment by Emilinya** [comment]
Fixed in commit [36c051c](https://github.com/Emilinya/Letterboxinator/commit/36c051cb4ba321ceb0182f96e6ed064754f180c3)
